version: 2.1

orbs:
  node: circleci/node@5.0.3
  gcp-gcr: circleci/gcp-gcr@0.6.1

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.14.1'
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --network-concurrency 1
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn build:ts
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.14.1'
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test

  dockerize:
    executor: gcp-gcr/default
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: .
      - gcp-gcr/gcr-auth
      - run:
          name: Build and push Docker image
          command: |
            docker build -t gcr.io/$GOOGLE_PROJECT_ID/hust-services-template:${CIRCLE_SHA1} .
            docker push gcr.io/$GOOGLE_PROJECT_ID/hust-services-template:${CIRCLE_SHA1}

workflows:
  build-test-and-dockerize:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - develop
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - develop
      - dockerize:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - develop
